### ISSUE TITLE
Unit Testing  - Compiler Directives

### ISSUE THREAD

**Issue by tinmanse** [rubberduck-vba/Battleship#15]
Could you use Compiler Directives to require the Rubberduck add-in only during Unit Testing?
#Const UnitTestMode = False
Public Const UnitTestMode As Boolean = False
#If UnitTestMode Then
    Private Assert As Rubberduck.AssertClass
#Else
    Private Assert As Object
#End If

**Comment by retailcoder** [comment]
Rubberduck's type library is late-bound, so RD is already not required for running non-test code paths. The advantage of using precompiler directives would be to enable early-binding (and thus intellisense) - but then if RD is early-bound, it needs to be referenced... and if RD isn't installed, then it becomes a missing reference, which breaks the "doesn't require Rubberduck to run" premise, because then the project won't be compilable/runnable.

So no, we can't do that: `Rubberduck.AssertClass` *must* be late-bound.
